site_name: Conia Error
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
    name: conia
repo_url: https://github.com/coniadev/error
extra:
    project: Http
plugins:
    - search
    - macros:
        module_name: docs/main
